// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StepUpLeadCareersTask.Models;

namespace StepUpLeadCareersTask.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20201101124259_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StepUpLeadCareersTask.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("JobDepartment")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LinkPageUrl")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("UserBrowserDetails")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("UserIpAddress")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("UserOsInfroamtion")
                        .HasColumnType("varchar(300)");

                    b.HasKey("CompanyId");

                    b.ToTable("Comapanys");
                });
#pragma warning restore 612, 618
        }
    }
}
